version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore(deps)"
    reviewers:
      - "jules-swe" # Replace with your GitHub username or team
